### ISSUE TITLE
User Feedback when cart is doing work

### ISSUE THREAD

**Issue by UVLabs** [fluid-checkout/fluid-checkout#146]
I have some ajax work happening while customers are doing various map related actions, I noticed that your plugin does not give user feedback (loading animations, spinning wheels etc) while operations are taking place in the background. Such as calling `update_checkout` trigger

In the following video I have a feature enabled in my plugin that dynamically updates the shipping price based on the customers location: https://share.vidyard.com/watch/oK9uzTAV8V6mvCF3ba2qQv?

You can see that the price is updating as it should, but because there's no user feedback by FC...you can't tell that work is taking place.

But in the default WC it gives clear feedback that work is happening: https://share.vidyard.com/watch/FMTA4u1nCAsntnSeF6wpzP

Is this by design? If so, is there a particular event or something I can have my plugin call so that user feedback can be shown in FC?

**Comment by UVLabs** [comment]
related https://github.com/fluidweb-co/fluid-checkout/issues/146

**Comment by diegoversiani** [comment]
Hi @UVLabs,

Fluid Checkout does not add the loading/processing indicator as we consider this responsibility of the theme. Many themes add this visual feedback and many don't.

We'll see if we can replace that indication with our own code in future releases.

1. Is there any indication of loading/processing when Fluid Checkout is deactivated, while using the same theme?

Sorry for the long wait on this, things have been hectic over here for quite a while.

Best,
Diego.

**Comment by diegoversiani** [comment]
Hi @UVLabs,

Finally was able to prioritize this. The fixes will be available with the next version (3.1.6+) which is set to be released in a couple of days.

I'm closing this issue for now. I'll be disabling the ability for everyone to open new issues here on Github, if you need anything please use our main support channel:
https://fluidcheckout.com/support/

Best,
Diego.
